'use strict';

var fs = require('fs');
var path = require('path');

var ROOT = __dirname;
var DIST = path.join(ROOT, 'dist');
var ENTRIES = JSON.parse(fs.readFileSync(path.join(ROOT, 'src', 'entries.json'), 'utf8'));
var ROWS = 20000;

function keyFor(i) {
  return ENTRIES.prefixes[i % ENTRIES.prefixes.length] + '-' + i;
}

function labelFor(i) {
  return ENTRIES.labels[i % ENTRIES.labels.length] + ' #' + i;
}

function main() {
  fs.mkdirSync(DIST, { recursive: true });
  var out = fs.createWriteStream(path.join(DIST, 'bundle.js'));

  out.write("'use strict';\n");
  out.write('// generated by build.js -- do not edit\n');
  out.write('var TABLE = [];\n');
  for (var i = 0; i < ROWS; i++) {
    out.write('TABLE.push({ id: ' + i + ", key: '" + keyFor(i) +
      "', label: '" + labelFor(i) + "' });\n");
  }
  out.write('function lookup(key) {\n');
  out.write('  for (var i = 0; i < TABLE.length; i++) {\n');
  out.write('    if (TABLE[i].key === key) return TABLE[i];\n');
  out.write('  }\n');
  out.write('  return null;\n');
  out.write('}\n');
  out.write('module.exports = { TABLE: TABLE, lookup: lookup };\n');
  out.end();

  console.log('built dist/bundle.js (' + ROWS + ' rows)');
  process.exit(0);
}

main();
