'use strict';

var fs = require('fs');
var path = require('path');

var ROOT = __dirname;
var SRC = path.join(ROOT, 'src');
var DIST = path.join(ROOT, 'dist');

function main() {
  var files = fs.readdirSync(SRC)
    .filter(function (name) { return name.slice(-3) === '.js'; })
    .sort();

  var parts = [
    '// generated by build.js -- do not edit',
    "'use strict';",
    'var CLI = {};',
    ''
  ];

  files.forEach(function (name) {
    parts.push('// ---- ' + name + ' ----');
    parts.push(fs.readFileSync(path.join(SRC, name), 'utf8').trim());
    parts.push('');
  });

  parts.push('module.exports = CLI;');

  fs.mkdirSync(DIST, { recursive: true });
  fs.writeFileSync(path.join(DIST, 'bundle.js'), parts.join('\n') + '\n');
  console.log('built dist/bundle.js from ' + files.length + ' modules');
}

main();
